src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = self::STATUS_CART;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\OneToMany(mappedBy: 'myOrder', targetEntity: OrderItem::class, cascade: ["persist", "remove"], orphanRemoval:true)]
    private Collection $orderItems;

    #[ORM\ManyToOne(inversedBy: 'orders', cascade: ["persist", "remove"])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $carrierName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?float $carrierPrice = null;

    #[ORM\Column(length: 25, nullable: true)]
    private ?string $delivery = null;

    #[ORM\Column(length: 255)]
    private ?string $reference = null;

    #[ORM\Column]
    private ?int $state = null;

    public function __construct()
    {
        $this->orderItems = new ArrayCollection();
    }


    /**
     * An order that is in progress, not placed yet.
     * 
     * @var string
     */
    public const STATUS_CART = 'cart';


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|OrderItem[]
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    public function addOrderItem(OrderItem $orderItem): self
        {
            foreach ($this->getOrderItems() as $existItem) {
                // The Item already exists, update the quantity
                if ($existItem->verif($orderItem)) {
                    $existItem->setQuantity(
                        $existItem->getQuantity() + $orderItem->getQuantity()
                    );

                    return $this;
                }
            }

            $this->orderItems[] = $orderItem;
            $orderItem->setMyOrder($this);

            return $this;
        }


    public function removeOrderItem(OrderItem $orderItem): self
    {
        if ($this->orderItems->removeElement($orderItem)) {
            // set the owning side to null (unless already changed)
            if ($orderItem->getMyOrder() === $this) {
                $orderItem->setMyOrder(null);
            }
        }

        return $this;
    }

        /**
         * Removes all items from the order.
         * 
         * @return $this
         */
        public function removeOrderItems(): self
        {
            foreach ($this->getOrderItems() as $orderItem) {
                $this->removeOrderItem($orderItem);
            }
            return $this;
        }

    /**
     * Calculates the order total.
     */
    public function getTotaux(): float
    {
        $total = 0;

        foreach ($this->getOrderItems() as $orderItem) {
            $total += $orderItem->getTotaux();
        }

        return $total;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCarrierName(): ?string
    {
        return $this->carrierName;
    }

    public function setCarrierName(string $carrierName): static
    {
        $this->carrierName = $carrierName;

        return $this;
    }

    public function getCarrierPrice(): ?string
    {
        return $this->carrierPrice;
    }

    public function setCarrierPrice(string $carrierPrice): static
    {
        $this->carrierPrice = $carrierPrice;

        return $this;
    }

    public function getDelivery(): ?string
    {
        return $this->delivery;
    }

    public function setDelivery(string $delivery): static
    {
        $this->delivery = $delivery;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(int $state): static
    {
        $this->state = $state;

        return $this;
    }
    
   
}

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Order;
use App\Form\EventListener\ClearCartListener;
use App\Form\EventListener\RemoveCartItemListener;
use App\Storage\CartSessionStorage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CartType extends AbstractType
{

    private $cartSessionStorage;

    public function __construct(CartSessionStorage $cartSessionStorage)
    {
        $this->cartSessionStorage = $cartSessionStorage;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('orderItems', CollectionType::class, [
                'entry_type' => CartItemType::class,
            ])
            ->add('save', SubmitType::class)
            ->add('clear', SubmitType::class);
            
        $builder->addEventSubscriber(new RemoveCartItemListener($this->cartSessionStorage));
        $builder->addEventSubscriber(new ClearCartListener($this->cartSessionStorage));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Form\CartType;
use App\Manager\CartManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{
    #[Route('/cart', name: 'cart')]
    public function index(CartManager $cartManager, Request $request): Response
    {
        $cartItems = $cartManager->getCurrentCart(); // Récupère les articles actuellement dans le panier
        $form = $this->createForm(CartType::class);

        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $cartManager->saveCart(); // Sauvegarde le panier mis à jour dans la session
            return $this->redirectToRoute('cart');

        }

        dd($cartItems);

        return $this->render('cart/index.html.twig', [
            'cartItems' => $cartItems,
            'form' => $form->createView(),
        ]);
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CartController!{% endblock %}

{% block content %}

 <!-- Page Title-->
 {% if form.orderItems|length >0 %}
      <div class="page-title-overlap bg-dark pt-4">
        <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
          <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb breadcrumb-light flex-lg-nowrap justify-content-center justify-content-lg-start">
                <li class="breadcrumb-item"><a class="text-nowrap" href="index.html"><i class="ci-home"></i>Home</a></li>
                <li class="breadcrumb-item text-nowrap"><a href="shop-grid-ls.html">Shop</a>
                </li>
                <li class="breadcrumb-item text-nowrap active" aria-current="page">Cart</li>
              </ol>
            </nav>
          </div>
          <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
            <h1 class="h3 text-light mb-0">Your cart</h1>
          </div>
        </div>
      </div>
      <div class="container pb-5 mb-2 mb-md-4">
        <div class="row">
          <!-- List of items-->
          <section class="col-lg-8">
          {{ form_start(form) }}
            <div class="d-flex justify-content-between align-items-center pt-3 pb-4 pb-sm-5 mt-1">
              <h2 class="h6 text-light mb-0">Products</h2><a class="btn btn-outline-primary btn-sm ps-2" href="shop-grid-ls.html"><i class="ci-arrow-left me-2"></i>Continue shopping</a>
              {{ form_widget(form.clear, {'attr': {'class': 'btn btn-outline-info'}}) }}
            </div>
            {% for item in form.orderItems %}
            <!-- Item-->
            <div class="d-sm-flex justify-content-between align-items-center my-2 pb-3 border-bottom">
              <div class="d-block d-sm-flex align-items-center text-center text-sm-start"><a class="d-inline-block flex-shrink-0 mx-auto me-sm-4" href="shop-single-v1.html"><img src="/upload\images\products\{{ item.vars.data.shopProduct.illustration}}" width="160" alt="Product"></a>
                <div class="pt-2">
                  <h3 class="product-title fs-base mb-2"><a href="shop-single-v1.html">{{ item.vars.data.shopProduct.name}}</a></h3>
                  <div class="fs-sm"><span class="text-muted me-2">Size:</span>{{ item.vars.data.size }}</div>
                  <div class="fs-sm"><span class="text-muted me-2">Color:</span>{{ item.vars.data.color }}</div>
                  <div class="fs-lg text-accent pt-2">{{ (item.vars.data.shopProduct.price / 100)|number_format(0, '',' ')  }}<small> F CFA</small></div>
                </div>
              </div>
              <div class="pt-2 pt-sm-0 ps-sm-3 mx-auto mx-sm-0 text-center text-sm-start" style="max-width: 9rem;">
                {{ form_widget(item.quantity, {'attr': {'class': 'form-control ' ~ (item.quantity.vars.valid ? '' : 'is-invalid')} }) }}
                <div class="invalid-feedback">
                {{ form_errors(item.quantity) }}
                </div>
                {{ form_widget(item.remove, {'attr': {'class': 'btn btn-link px-0 text-danger'}}) }}
              </div>
            </div>
            {% endfor %}
             {{ form_widget(form.save, {'attr': {'class': 'btn btn-outline-accent d-block w-100 mt-4'}}) }}
             {{ form_end(form, {'render_rest': false}) }}
          </section>
          <!-- Sidebar-->
          <aside class="col-lg-4 pt-4 pt-lg-0 ps-xl-5">
            <div class="bg-white rounded-3 shadow-lg p-4">
              <div class="py-2 px-xl-2">
                <div class="text-center mb-4 pb-3 border-bottom">
                  <h2 class="h6 mb-3 pb-1">Subtotal</h2>
                  <h3 class="fw-normal">{{ (cart.totaux / 100)|number_format(0, '',' ') }}<small> F CFA</small></h3>
                </div>
                <div class="mb-3 mb-4">
                  <label class="form-label mb-3" for="order-comments"><span class="badge bg-info fs-xs me-2">Note</span><span class="fw-medium">Additional comments</span></label>
                  <textarea class="form-control" rows="6" id="order-comments"></textarea>
                </div>
                <div class="accordion" id="order-options">
                  <div class="accordion-item">
                    <h3 class="accordion-header"><a class="accordion-button" href="#promo-code" role="button" data-bs-toggle="collapse" aria-expanded="true" aria-controls="promo-code">Apply promo code</a></h3>
                    <div class="accordion-collapse collapse show" id="promo-code" data-bs-parent="#order-options">
                      <form class="accordion-body needs-validation" method="post" novalidate>
                        <div class="mb-3">
                          <input class="form-control" type="text" placeholder="Promo code" required>
                          <div class="invalid-feedback">Please provide promo code.</div>
                        </div>
                        <button class="btn btn-outline-primary d-block w-100" type="submit">Apply promo code</button>
                      </form>
                    </div>
                  </div>
                </div><a class="btn btn-primary btn-shadow d-block w-100 mt-4" href="{{ path('order') }}"><i class="ci-card fs-lg me-2"></i>Proceed to Checkout</a>
              </div>
            </div>
          </aside>
        </div>
        {% else %}
         <div class="container py-5 mb-lg-3">
        <div class="row justify-content-center pt-lg-4 text-center">
          <div class="col-lg-5 col-md-7 col-sm-9"><img class="d-block mx-auto mb-5" src="{{ asset('assets/img/pages/404.png') }}" width="340" alt="404 Error">
            <h1 class="h3">Désolé, votre panier est vide pour le moment. </h1>
            <h3 class="h5 fw-normal mb-4">Nous vous invitons à parcourir notre catalogue pour trouver les produits qui vous intéressent. </h3>
            <p class="fs-md mb-4">
              <u>Si vous avez des questions ou besoin d'aide, notre équipe est là pour vous assister.</u>
            </p>
          </div>
        </div>
        <div class="row justify-content-center pt-lg-4 text-center">
          <div class="col-xl-8 col-lg-10">
            <div class="row">
              <div class="col-sm-4 mb-3"><a class="card h-100 border-0 shadow-sm" href="{{ path('home')}}">
                  <div class="card-body">
                    <div class="d-flex align-items-center"><i class="ci-home text-primary h4 mb-0"></i>
                      <div class="ps-3">
                        <h5 class="fs-sm mb-0">Homepage</h5><span class="text-muted fs-ms">Return to homepage</span>
                      </div>
                    </div>
                  </div></a></div>
              <div class="col-sm-4 mb-3"><a class="card h-100 border-0 shadow-sm" href="#">
                  <div class="card-body">
                    <div class="d-flex align-items-center"><i class="ci-help text-info h4 mb-0"></i>
                      <div class="ps-3">
                        <h5 class="fs-sm mb-0">Help &amp; Support</h5><span class="text-muted fs-ms">Visit our help center</span>
                      </div>
                    </div>
                  </div></a></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endif %}

{% endblock %}